package com.example.shardingjdbcdemo.model;

public class OrderItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item1.id
     *
     * @mbg.generated Fri Jul 03 09:03:34 GMT+08:00 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item1.order_id
     *
     * @mbg.generated Fri Jul 03 09:03:34 GMT+08:00 2020
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_item1.item_name
     *
     * @mbg.generated Fri Jul 03 09:03:34 GMT+08:00 2020
     */
    private String itemName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item1.id
     *
     * @return the value of t_order_item1.id
     *
     * @mbg.generated Fri Jul 03 09:03:34 GMT+08:00 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item1.id
     *
     * @param id the value for t_order_item1.id
     *
     * @mbg.generated Fri Jul 03 09:03:34 GMT+08:00 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item1.order_id
     *
     * @return the value of t_order_item1.order_id
     *
     * @mbg.generated Fri Jul 03 09:03:34 GMT+08:00 2020
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item1.order_id
     *
     * @param orderId the value for t_order_item1.order_id
     *
     * @mbg.generated Fri Jul 03 09:03:34 GMT+08:00 2020
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_item1.item_name
     *
     * @return the value of t_order_item1.item_name
     *
     * @mbg.generated Fri Jul 03 09:03:34 GMT+08:00 2020
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_item1.item_name
     *
     * @param itemName the value for t_order_item1.item_name
     *
     * @mbg.generated Fri Jul 03 09:03:34 GMT+08:00 2020
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }
}